{"cheat": [], "no_reward": [], "exception": [{"config": "Allan Schwantd", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=William.Martin.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Amos Linnan", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Michael.Levy.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Andrew Jackson", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 156, in table_api_call\n    response.raise_for_status()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 132, in setup\n    self._base_user_name, self._base_user_password, self._base_user_sysid = create_user(\n                                                                            ^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/user.py\", line 55, in create_user\n    user_response = table_api_call(\n                    ^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 159, in table_api_call\n    raise HTTPError(f\"{e} | status={response.status_code} url={response.url} body={snippet!r}\")\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True | status=403 url=https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True body='{\"error\":{\"message\":\"Operation Failed\",\"detail\":\"Error during insert of sys_user (Christopher Johnson)\"},\"status\":\"failure\"}'\n"}, {"config": "Andrew Och", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Zoe.Barnes.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Armando Kolm", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Rebecca.Cook.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Ashley Parker", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Jason.Kemp.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Audra Cantu", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Jason.Trujillo.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Benjamin Schkade", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Benjamin Schkade\").first\n\n"}, {"config": "Bernard Laboy", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Brian.Johnson.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Bertram Quertermous", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Jimmy.Johnson.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Bette Barcelona", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Karen.Gomez.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Billie Tinnes", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Joseph.Ortega.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Brant Darnel", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Brant Darnel\").first\n  -   locator resolved to <div role=\"option\" aria-setsize=\"1\" aria-posinset=\"1\"\u2026>\u2026</div>\n  - attempting click action\n  -   waiting for element to be visible, enabled and stable\n  - element was detached from the DOM, retrying\n\n"}, {"config": "Brice Hedglin", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Charles.Mullen.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Bushra Akhtar", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Carrie.Rivera.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Callie Leboeuf", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Kathryn.Vega.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Cameron Richard", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Denise.Hubbard.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Candice Bruckman", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Amanda.Williams.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Carla Humble", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Carla Humble\").first\n\n"}, {"config": "Chad Miklas", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Chad Miklas\").first\n\n"}, {"config": "Change Manager", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Chris.Robinson.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Chase Furler", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 156, in table_api_call\n    response.raise_for_status()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 132, in setup\n    self._base_user_name, self._base_user_password, self._base_user_sysid = create_user(\n                                                                            ^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/user.py\", line 55, in create_user\n    user_response = table_api_call(\n                    ^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 159, in table_api_call\n    raise HTTPError(f\"{e} | status={response.status_code} url={response.url} body={snippet!r}\")\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True | status=403 url=https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True body='{\"error\":{\"message\":\"Operation Failed\",\"detail\":\"Error during insert of sys_user (Chelsea Moore)\"},\"status\":\"failure\"}'\n"}, {"config": "Claire Moyerman", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Debra.Copeland.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Curt Menedez", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Victoria.Brown.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Danette Fostervold", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 156, in table_api_call\n    response.raise_for_status()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 132, in setup\n    self._base_user_name, self._base_user_password, self._base_user_sysid = create_user(\n                                                                            ^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/user.py\", line 55, in create_user\n    user_response = table_api_call(\n                    ^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 159, in table_api_call\n    raise HTTPError(f\"{e} | status={response.status_code} url={response.url} body={snippet!r}\")\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True | status=403 url=https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True body='{\"error\":{\"message\":\"Operation Failed\",\"detail\":\"Error during insert of sys_user (Sarah Barnes)\"},\"status\":\"failure\"}'\n"}, {"config": "Eric Schroeder", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 156, in table_api_call\n    response.raise_for_status()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 132, in setup\n    self._base_user_name, self._base_user_password, self._base_user_sysid = create_user(\n                                                                            ^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/user.py\", line 55, in create_user\n    user_response = table_api_call(\n                    ^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 159, in table_api_call\n    raise HTTPError(f\"{e} | status={response.status_code} url={response.url} body={snippet!r}\")\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True | status=403 url=https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True body='{\"error\":{\"message\":\"Operation Failed\",\"detail\":\"Error during insert of sys_user (Kristina Thomas)\"},\"status\":\"failure\"}'\n"}, {"config": "Fred Kunde", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=David.Watson.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Hilario Cassa", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Hilario Cassa\").first\n\n"}, {"config": "Howard Johnson", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Justin.Jordan.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Ike Benthin", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Ian.Curtis.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Jessie Barkle", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 153, in setup\n    self.start(page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 177, in start\n    url_login(\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 92, in url_login\n    page.goto(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 8686, in goto\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://myarena25demo.service-now.com/login.do?user_name=Paul.Powell.1235&user_password=aStrongPassword%21&sys_action=sysverb_login\", waiting until \"load\"\n\n"}, {"config": "Joe Employee", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 156, in table_api_call\n    response.raise_for_status()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 159, in validate_on_page\n    task.setup(page=page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/base.py\", line 132, in setup\n    self._base_user_name, self._base_user_password, self._base_user_sysid = create_user(\n                                                                            ^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/user.py\", line 55, in create_user\n    user_response = table_api_call(\n                    ^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/api/utils.py\", line 159, in table_api_call\n    raise HTTPError(f\"{e} | status={response.status_code} url={response.url} body={snippet!r}\")\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True | status=403 url=https://myarena25demo.service-now.com/api/now/table/sys_user?sysparm_input_display_value=True body='{\"error\":{\"message\":\"Operation Failed\",\"detail\":\"Error during insert of sys_user (Jessica Johnson)\"},\"status\":\"failure\"}'\n"}, {"config": "Mandy Mcdonnell", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Mandy Mcdonnell\").first\n\n"}, {"config": "Meredith Ivrin", "reason": "Traceback (most recent call last):\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 216, in validate_configs\n    task_done, reward, task_config, cheat_passed = validate_task(\n                                                   ^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 338, in wrapped_f\n    return copy(f, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 477, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/tenacity/__init__.py\", line 480, in __call__\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 137, in validate_task\n    cheat_passed, task_done, reward = validate_on_page(task_class, task_config, page)\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/tests/test_yoko.py\", line 161, in validate_on_page\n    task.cheat(page=page, chat_messages=chat_messages)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/tasks/navigation.py\", line 200, in cheat\n    impersonate_user(self.user_full_name, page)\n  File \"/Users/dheeraj.vattikonda/Desktop/WORKARENA_2/WorkArena/src/browsergym/workarena/utils.py\", line 33, in impersonate_user\n    page.locator(\"seismic-hoist\").get_by_role(\"option\", name=username).first.click()\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/sync_api/_generated.py\", line 14929, in click\n    self._sync(\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_locator.py\", line 156, in click\n    return await self._frame.click(self._selector, strict=True, **params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/dheeraj.vattikonda/miniconda/envs/myenv/lib/python3.11/site-packages/playwright/_impl/_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"seismic-hoist\").get_by_role(\"option\", name=\"Meredith Ivrin\").first\n\n"}], "not_done": []}